export default {
    products: [{
            _id: '1',
            name: 'Sonpapdi',
            category: 'Shirts',
            image: 'images/sw2.jpg',
            price: 69,
            brand: 'Chitale Bandhu',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Malayi Pedha',
            category: 'Shirts',
            image: 'images/sw3.jpg',
            price: 70,
            brand: 'Haldirams',
            rating: 5,
            numReviews: 51,
        },
        {
            _id: '3',
            name: 'Kaju Katli',
            category: 'Shirts',
            image: 'images/sw4.jpg',
            price: 59,
            brand: 'Welcomes',
            rating: 4,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Kesar Pedha',
            category: 'Pants',
            image: 'images/sw6.jpg',
            price: 90,
            brand: 'Balaji',
            rating: 2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Kaju Katli',
            category: 'Shirts',
            image: 'images/sw4.jpg',
            price: 59,
            brand: 'Welcomes',
            rating: 4,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Kesar Pedha',
            category: 'Pants',
            image: 'images/sw6.jpg',
            price: 90,
            brand: 'Balaji',
            rating: 2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '1',
            name: 'Sonpapdi',
            category: 'Shirts',
            image: 'images/sw2.jpg',
            price: 69,
            brand: 'Chitale Bandhu',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Malayi Pedha',
            category: 'Shirts',
            image: 'images/sw3.jpg',
            price: 70,
            brand: 'Haldirams',
            rating: 5,
            numReviews: 51,
        },
    ],
};